#!/usr/bin/env python3
"""
render_index.py — Generate cases/README.md and SVG charts from cases/*/meta.yaml.

Requires: PyYAML (`pip install pyyaml`)
Usage:    python3 scripts/render_index.py

Outputs:
  - cases/README.md             (auto-generated case index, grouped by category)
  - assets/category-chart.svg   (donut chart of category distribution)
  - assets/timeline.svg         (bar chart of cases by year)
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("ERROR: PyYAML required. Install with `pip install pyyaml`.\n")
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
CASES_DIR = ROOT / "cases"
ASSETS_DIR = ROOT / "assets"

CATEGORIES: dict[str, str] = {
    "supply-chain":    "Hallucination & Supply Chain",
    "code-vulns":      "Code-Level Vulnerabilities",
    "cloud-iac":       "Cloud & IaC Misconfiguration",
    "agent-risk":      "Agent Risks",
    "domain-specific": "Domain-Specific Risks",
    "ip-compliance":   "IP, License & Compliance",
    "human-factor":    "Human Factors",
}

SEVERITY_EMOJI = {
    "critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢", "info": "⚪",
}

CAT_COLORS = {
    "supply-chain":    "#3b82f6",
    "code-vulns":      "#ef4444",
    "cloud-iac":       "#0ea5e9",
    "agent-risk":      "#a855f7",
    "domain-specific": "#f59e0b",
    "ip-compliance":   "#10b981",
    "human-factor":    "#64748b",
}


def load_cases() -> list[dict]:
    cases = []
    for meta_file in CASES_DIR.glob("*/meta.yaml"):
        if meta_file.parent.name == "_template":
            continue
        data = yaml.safe_load(meta_file.read_text(encoding="utf-8"))
        if data and data.get("slug"):
            cases.append(data)
    return sorted(cases, key=lambda c: (c["year"], c["slug"]))


def render_index(cases: list[dict]) -> str:
    by_cat: dict[str, list[dict]] = {}
    for c in cases:
        by_cat.setdefault(c["category"], []).append(c)

    out = [
        "# Case Index / 案例索引",
        "",
        f"**{len(cases)} cases** across **{len(CATEGORIES)} categories**, spanning "
        f"**{cases[0]['year']}–{cases[-1]['year']}**.",
        "",
        "> Auto-generated by `scripts/render_index.py`. Edit `meta.yaml` files, then re-run.",
        "",
    ]
    for cat_key, display in CATEGORIES.items():
        if cat_key not in by_cat:
            continue
        out += [
            f"## {display}",
            "",
            "| Year | Title | Severity | AI Tool | CVE |",
            "|---|---|---|---|---|",
        ]
        for c in sorted(by_cat[cat_key], key=lambda x: x["year"]):
            sev_emoji = SEVERITY_EMOJI.get(c.get("severity", ""), "⚪")
            sev = f"{sev_emoji} {c.get('severity', '—')}"
            ai = ", ".join(c.get("ai_tool") or []) or "—"
            cve = c.get("cve") or "—"
            link = f"[{c['title_en']}](./{c['slug']}/)"
            out.append(f"| {c['year']} | {link} | {sev} | {ai} | {cve} |")
        out.append("")
    return "\n".join(out)


def render_category_svg(cases: list[dict]) -> str:
    counts: dict[str, int] = {}
    for c in cases:
        counts[c["category"]] = counts.get(c["category"], 0) + 1
    total = sum(counts.values())

    cx, cy, r, w = 200, 200, 130, 42
    svg: list[str] = [
        '<svg xmlns="http://www.w3.org/2000/svg" '
        'width="720" height="400" viewBox="0 0 720 400" '
        'preserveAspectRatio="xMidYMid meet" '
        'font-family="Arial, Helvetica, sans-serif">',
    ]

    angle = -math.pi / 2
    for cat_key in CATEGORIES:
        count = counts.get(cat_key, 0)
        if not count:
            continue
        sweep = 2 * math.pi * count / total
        end = angle + sweep
        x1, y1 = cx + r * math.cos(angle), cy + r * math.sin(angle)
        x2, y2 = cx + r * math.cos(end), cy + r * math.sin(end)
        x3, y3 = cx + (r - w) * math.cos(end), cy + (r - w) * math.sin(end)
        x4, y4 = cx + (r - w) * math.cos(angle), cy + (r - w) * math.sin(angle)
        large = 1 if sweep > math.pi else 0
        d = (
            f"M {x1:.2f} {y1:.2f} A {r} {r} 0 {large} 1 {x2:.2f} {y2:.2f} "
            f"L {x3:.2f} {y3:.2f} A {r - w} {r - w} 0 {large} 0 {x4:.2f} {y4:.2f} Z"
        )
        svg.append(f'<path d="{d}" fill="{CAT_COLORS[cat_key]}" />')
        angle = end

    svg.append(
        f'<text x="{cx}" y="{cy - 4}" text-anchor="middle" font-size="56" font-weight="700">{total}</text>'
    )
    svg.append(
        f'<text x="{cx}" y="{cy + 24}" text-anchor="middle" font-size="14" fill="#666">cases</text>'
    )

    y = 64
    for cat_key, display in CATEGORIES.items():
        n = counts.get(cat_key, 0)
        if not n:
            continue
        svg.append(
            f'<rect x="420" y="{y}" width="16" height="16" rx="3" fill="{CAT_COLORS[cat_key]}"/>'
        )
        svg.append(
            f'<text x="446" y="{y + 13}" font-size="14">{display} '
            f'<tspan fill="#666">({n})</tspan></text>'
        )
        y += 30

    svg.append("</svg>")
    return "\n".join(svg)


def render_timeline_svg(cases: list[dict]) -> str:
    years: dict[int, int] = {}
    for c in cases:
        years[c["year"]] = years.get(c["year"], 0) + 1
    if not years:
        return ""
    yr_min, yr_max = min(years), max(years)

    width, height, margin = 720, 360, 60
    n_years = yr_max - yr_min + 1
    bar_slot = (width - 2 * margin) / n_years
    max_count = max(years.values())

    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{width}" height="{height}" viewBox="0 0 {width} {height}" '
        f'preserveAspectRatio="xMidYMid meet" '
        f'font-family="Arial, Helvetica, sans-serif">',
        f'<text x="{width / 2}" y="32" text-anchor="middle" font-size="18" font-weight="700">'
        "Cases by Year</text>",
    ]

    plot_h = height - margin - 80
    baseline = height - margin
    for i, yr in enumerate(range(yr_min, yr_max + 1)):
        count = years.get(yr, 0)
        h = (count / max_count) * plot_h if count else 0
        x = margin + i * bar_slot + bar_slot * 0.18
        bw = bar_slot * 0.64
        y = baseline - h
        if count:
            svg.append(
                f'<rect x="{x:.1f}" y="{y:.1f}" width="{bw:.1f}" height="{h:.1f}" '
                f'rx="4" fill="#ef4444" />'
            )
            svg.append(
                f'<text x="{x + bw / 2:.1f}" y="{y - 8:.1f}" text-anchor="middle" '
                f'font-size="14" font-weight="700">{count}</text>'
            )
        svg.append(
            f'<text x="{x + bw / 2:.1f}" y="{baseline + 24}" text-anchor="middle" '
            f'font-size="14" fill="#444">{yr}</text>'
        )

    svg.append(
        f'<line x1="{margin}" y1="{baseline}" x2="{width - margin}" y2="{baseline}" '
        f'stroke="#333" stroke-width="1.5"/>'
    )
    svg.append("</svg>")
    return "\n".join(svg)


def render_category_png(cases: list[dict], out_path: Path) -> bool:
    """Generate a PNG donut chart. Returns True on success, False if Pillow missing."""
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        return False

    counts: dict[str, int] = {}
    for c in cases:
        counts[c["category"]] = counts.get(c["category"], 0) + 1
    total = sum(counts.values())

    W, H = 1440, 800  # 2x SVG dims for retina; downscale at display time
    SCALE = 2
    img = Image.new("RGB", (W, H), "white")
    draw = ImageDraw.Draw(img)

    # Donut: outer r=260, inner r=176, center (400, 400)
    cx, cy, r_out, r_in = 400, 400, 260, 176
    bbox_out = (cx - r_out, cy - r_out, cx + r_out, cy + r_out)
    bbox_in = (cx - r_in, cy - r_in, cx + r_in, cy + r_in)

    angle = -90.0
    for cat_key in CATEGORIES:
        n = counts.get(cat_key, 0)
        if not n:
            continue
        sweep = 360.0 * n / total
        end = angle + sweep
        draw.pieslice(bbox_out, angle, end, fill=CAT_COLORS[cat_key])
        angle = end
    # Donut hole
    draw.ellipse(bbox_in, fill="white")

    # Try to load a usable font
    def _font(size: int):
        for path in [
            "/System/Library/Fonts/Helvetica.ttc",
            "/System/Library/Fonts/HelveticaNeue.ttc",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/Library/Fonts/Arial.ttf",
        ]:
            if Path(path).exists():
                try:
                    return ImageFont.truetype(path, size)
                except OSError:
                    continue
        return ImageFont.load_default()

    f_big = _font(112 * SCALE // 2)  # ~112
    f_sm = _font(28 * SCALE // 2)    # ~28
    f_legend = _font(28 * SCALE // 2)

    # Center text
    tot_text = str(total)
    bb = draw.textbbox((0, 0), tot_text, font=f_big, anchor="lt")
    tw = bb[2] - bb[0]
    th = bb[3] - bb[1]
    draw.text((cx - tw // 2, cy - th // 2 - 10), tot_text, fill="#111", font=f_big)
    draw.text((cx, cy + th // 2 + 6), "cases", fill="#666", font=f_sm, anchor="mt")

    # Legend (right side)
    lx = 840
    ly = 150
    box_size = 32
    line_h = 56
    for cat_key, display in CATEGORIES.items():
        n = counts.get(cat_key, 0)
        if not n:
            continue
        draw.rounded_rectangle(
            (lx, ly, lx + box_size, ly + box_size),
            radius=6,
            fill=CAT_COLORS[cat_key],
        )
        draw.text(
            (lx + box_size + 16, ly + box_size // 2),
            f"{display}  ({n})",
            fill="#222",
            font=f_legend,
            anchor="lm",
        )
        ly += line_h

    img.save(out_path, "PNG", optimize=True)
    return True


def render_timeline_png(cases: list[dict], out_path: Path) -> bool:
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        return False

    years: dict[int, int] = {}
    for c in cases:
        years[c["year"]] = years.get(c["year"], 0) + 1
    if not years:
        return False
    yr_min, yr_max = min(years), max(years)
    n_years = yr_max - yr_min + 1
    max_count = max(years.values())

    W, H = 1440, 720
    img = Image.new("RGB", (W, H), "white")
    draw = ImageDraw.Draw(img)

    def _font(size: int):
        for path in [
            "/System/Library/Fonts/Helvetica.ttc",
            "/System/Library/Fonts/HelveticaNeue.ttc",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/Library/Fonts/Arial.ttf",
        ]:
            if Path(path).exists():
                try:
                    return ImageFont.truetype(path, size)
                except OSError:
                    continue
        return ImageFont.load_default()

    f_title = _font(40)
    f_year = _font(28)
    f_count = _font(28)

    # Title
    draw.text((W // 2, 50), "Cases by Year", fill="#111", font=f_title, anchor="mt")

    # Plot area
    margin = 120
    baseline = H - margin
    plot_top = 130
    plot_h = baseline - plot_top
    plot_w = W - 2 * margin

    bar_slot = plot_w / n_years
    for i, yr in enumerate(range(yr_min, yr_max + 1)):
        count = years.get(yr, 0)
        h = int((count / max_count) * plot_h) if count else 0
        x = margin + i * bar_slot + bar_slot * 0.20
        bw = bar_slot * 0.60
        y = baseline - h
        if count:
            draw.rounded_rectangle(
                (x, y, x + bw, baseline),
                radius=8,
                fill="#ef4444",
            )
            draw.text(
                (x + bw / 2, y - 16),
                str(count),
                fill="#111",
                font=f_count,
                anchor="ms",
            )
        draw.text(
            (x + bw / 2, baseline + 16),
            str(yr),
            fill="#444",
            font=f_year,
            anchor="mt",
        )

    # Baseline
    draw.line(
        ((margin, baseline), (W - margin, baseline)),
        fill="#333",
        width=3,
    )

    img.save(out_path, "PNG", optimize=True)
    return True


def main() -> None:
    cases = load_cases()
    print(f"Loaded {len(cases)} cases")

    index_md = render_index(cases)
    (CASES_DIR / "README.md").write_text(index_md, encoding="utf-8")
    print(f"  → cases/README.md ({len(index_md)} bytes)")

    ASSETS_DIR.mkdir(exist_ok=True)
    cat_svg = render_category_svg(cases)
    (ASSETS_DIR / "category-chart.svg").write_text(cat_svg, encoding="utf-8")
    print(f"  → assets/category-chart.svg ({len(cat_svg)} bytes)")

    tl_svg = render_timeline_svg(cases)
    (ASSETS_DIR / "timeline.svg").write_text(tl_svg, encoding="utf-8")
    print(f"  → assets/timeline.svg ({len(tl_svg)} bytes)")

    cat_png = ASSETS_DIR / "category-chart.png"
    if render_category_png(cases, cat_png):
        print(f"  → assets/category-chart.png ({cat_png.stat().st_size} bytes)")
    else:
        print("  ⚠ Pillow not installed; skipping PNG charts")
        return

    tl_png = ASSETS_DIR / "timeline.png"
    if render_timeline_png(cases, tl_png):
        print(f"  → assets/timeline.png ({tl_png.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
